# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-04 18:42
from __future__ import unicode_literals

from decimal import Decimal
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('seats', models.PositiveIntegerField()),
                ('opening_time', models.PositiveIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(24)])),
                ('closing_time', models.PositiveIntegerField(default=21, validators=[django.core.validators.MaxValueValidator(24)])),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('3.00'))])),
                ('about', models.CharField(blank=True, max_length=2048)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('movie_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_available', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('slot', models.PositiveIntegerField()),
                ('movie_type', models.CharField(max_length=10)),
                ('movie_language', models.CharField(max_length=100)),
                ('audi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Auditorium')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=2048)),
                ('state', models.CharField(max_length=2048)),
                ('zipcode', models.PositiveIntegerField(null=True)),
                ('functional_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoriums', to='movies.Theatre'),
        ),
        migrations.AlterUniqueTogether(
            name='auditorium',
            unique_together=set([('name', 'theatre')]),
        ),
    ]
