# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-05 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190605_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.PositiveIntegerField(),
        ),
    ]
